module.exports = {
  DB_URI: process.env.DB_URI,
  AUTH0_NAMESPACE: process.env.AUTH0_NAMESPACE,
  AUTH0_TOKEN_URL: process.env.AUTH0_TOKEN_URL,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
  AUTH0_CLIENT_AUDIENCE: process.env.AUTH0_CLIENT_AUDIENCE,
  AUTH0_CLIENT_DOMAIN: process.env.AUTH0_CLIENT_DOMAIN,
  CLOUDINARY_NAME: process.env.CLOUDINARY_NAM,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
};
